apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jlmo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-jlmo@sha256:8d454193916283c7b66a1476d997c88b82b4f05cf02e4a18da903179002e9ff5
        name: my-nodejs
        resources: {}
status: {}
